version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
      - image: circleci/postgres:9.6-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler:2.1.4
      - ruby/bundle-install
      - run:
          name: database setup
          command: | 
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rake db:seed
      - run:
          name: check test code
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: test-results